"""add cleaned_text to reflections

Revision ID: 61051d22abea
Revises: a0b141fd0e6f
Create Date: 2026-05-09 20:57:42.292698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61051d22abea'
down_revision: Union[str, None] = 'a0b141fd0e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reflections', sa.Column('cleaned_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_reflections', 'cleaned_text')
    # ### end Alembic commands ###