"""initial tables

Revision ID: a0b141fd0e6f
Revises: 26b260b3a041
Create Date: 2026-05-04 15:09:03.951231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b141fd0e6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('accounting', 'maintenance', 'human_resources', 'it', 'sales', 'marketing', name='departmentnameenum'), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_department_id'), 'departments', ['department_id'], unique=False)
    op.create_table('department_alarms',
    sa.Column('alarm_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severityenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('negative_ratio', sa.Float(), nullable=False),
    sa.Column('analyses_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('alarm_id')
    )
    op.create_index(op.f('ix_department_alarms_alarm_id'), 'department_alarms', ['alarm_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('employee', 'manager', 'hr', name='roleenum'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_table('daily_reflections',
    sa.Column('reflection_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('wellness_tip', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('reflection_id')
    )
    op.create_index(op.f('ix_daily_reflections_reflection_id'), 'daily_reflections', ['reflection_id'], unique=False)
    op.create_table('sentiment_analyses',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('reflection_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='sentimentenum'), nullable=False),
    sa.Column('emotion', sa.Enum('happiness', 'stress', 'anger', 'motivation', 'neutral', 'sadness', 'cooperation', name='emotionenum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['reflection_id'], ['daily_reflections.reflection_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_sentiment_analyses_analysis_id'), 'sentiment_analyses', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_analyses_analysis_id'), table_name='sentiment_analyses')
    op.drop_table('sentiment_analyses')
    op.drop_index(op.f('ix_daily_reflections_reflection_id'), table_name='daily_reflections')
    op.drop_table('daily_reflections')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_department_alarms_alarm_id'), table_name='department_alarms')
    op.drop_table('department_alarms')
    op.drop_index(op.f('ix_departments_department_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###